# Ilitek V3 I2C TDDI driver for Raspberry Pi
obj-m += ilitek_v3_driver.o

ilitek_v3_driver-y := \
	ilitek_v3.o \
	ilitek_v3_i2c.o \
	ilitek_v3_rpi.o \
	ilitek_v3_ic.o \
	ilitek_v3_touch.o \
	ilitek_v3_mp.o \
	ilitek_v3_flash.o \
	ilitek_v3_node.o
